site_name: <%= $PLASTER_PARAM_ModuleName %>
repo_url: https://github.com/<%= $PLASTER_PARAM_GitHubUserName %>/<%= $PLASTER_PARAM_GitHubRepo %>
theme: readthedocs
pages:
- Home: index.md
- <%= $PLASTER_PARAM_ModuleName %> Basics:
  - What is <%= $PLASTER_PARAM_ModuleName %>: about.md
  - Quick Start: Quick-Start-Installation-and-Example.md
- Basic Commands:
- Examples:
- Acknowledgements: acknowledgements.md